### ISSUE TITLE
Docker quickstart fails deploying service.

### ISSUE THREAD

**Issue by BenjaminDavison** [Yelp/paasta#647] opened 2016-08-08 14:31 UTC
Hi all,

Just trying out the paasta quick start on my Linux (ubuntu 15.04) box. I followed the quickstart and have not been successful in deploying the test service.

```
root@69c9dc87e01c:/tmp/dockercloud-hello-world# paasta itest -s hello-world -c `git rev-parse HEAD`
root@69c9dc87e01c:/tmp/dockercloud-hello-world# paasta push-to-registry -s hello-world -c `git rev-parse HEAD`
root@69c9dc87e01c:/tmp/dockercloud-hello-world# paasta mark-for-deployment --git-url root@git:dockercloud-hello-world --commit `git rev-parse HEAD` --clusterinstance testcluster.everything --service hello-world

root@69c9dc87e01c:/tmp/dockercloud-hello-world# ls
Dockerfile  LICENSE  Makefile  README.md  docker-cloud.yml  docker-compose.yml  nginx.conf  php-fpm.conf  www
-----
root@69c9dc87e01c:/tmp/dockercloud-hello-world# paasta metastatus
Cluster: testcluster
No dashboards configured!
Warning: Permanently added '172.18.0.3' (ECDSA) to the list of known hosts.
Mesos Status: OK
Marathon Status: CRITICAL
Chronos Status: OK
-----
root@69c9dc87e01c:/tmp/dockercloud-hello-world# paasta status -s hello-world
Traceback (most recent call last):
  File "/usr/local/bin/paasta", line 9, in <module>
    load_entry_point('paasta-tools==0.34.4', 'console_scripts', 'paasta')()
  File "/work/paasta_tools/cli/cli.py", line 118, in main
    return_code = args.command(args)
  File "/work/paasta_tools/cli/cmds/status.py", line 215, in paasta_status
    actual_deployments = get_actual_deployments(service, soa_dir)
  File "/work/paasta_tools/cli/cmds/status.py", line 119, in get_actual_deployments
    deployments_json = load_deployments_json(service, soa_dir)
  File "/work/paasta_tools/utils.py", line 1333, in load_deployments_json
    raise NoDeploymentsAvailable
paasta_tools.utils.NoDeploymentsAvailable
root@69c9dc87e01c:/tmp/dockercloud-hello-world# 
```

I "think" it's something to-do with Marathon being in a critical state, but interestingly I can hit the mesos UI and see that chronos and marathon are running (marathon does not show any services etc)

Here's what I see in: /var/log/paasta_logs/hello-world.log

```
{"cluster": "N/A", "component": "build", "instance": "N/A", "level": "debug", "message": "", "service": "hello-world", "timestamp": "2016-08-08T14:22:10.067260"}
{"cluster": "N/A", "component": "build", "instance": "N/A", "level": "event", "message": "Successfully pushed image for 9cdf957d3fbbb61fa17388adb2d8e282446271fc to registry", "service": "hello-world", "timestamp": "2016-08-08T14:22:10.06
7918"}
{"cluster": "N/A", "component": "deploy", "instance": "N/A", "level": "event", "message": "Marked 9cdf957d3fbbb61fa17388adb2d8e282446271fc in for deployment in deploy group testcluster.everything", "service": "hello-world", "timestamp": 
"2016-08-08T14:22:16.175281"}
```

I shortened it to what I think are the most important sections (if you need to see anything else just shout)

I couldn't find the marathon logs (jumped onto the marathon docker container but couldn't find anything).

Thanks,

Ben

**Comment by solarkennedy** [comment] 2016-08-08 22:53
This is a brand new thing (the quickstart), this is the first bug report!

I think this is because we don't have cron building the deployments.json files on the "git" container?

**Comment by EvanKrall** [comment] 2016-08-09 02:38
Hm, generate_all_deployments is cron'd in the [mesos-paasta image](https://github.com/Yelp/paasta/blob/master/yelp_package/dockerfiles/mesos-paasta/cron.d/paasta_generate_all_deployments), which is what mesosmaster should be running, and the example-services directory is volume-mounted RW ...

Starting up the playground to dig in a bit.

**Comment by EvanKrall** [comment] 2016-08-09 03:05
Perhaps the issue is that the mesosmaster container (anything using the mesos-paasta image) is doing a bunch of work on startup before cron and mesos-master are started: https://github.com/Yelp/paasta/blob/master/yelp_package/dockerfiles/mesos-paasta/start.sh, which could cause cron to not start for a long time.

However, paasta metastatus says that mesos is healthy, and mesos-master starts after cron. Confusing.

I have to go home for the evening; maybe @mattmb can take a look.

**Comment by EvanKrall** [comment] 2016-08-09 03:16
Hm, after waiting for everything to finish starting up and running through the instructions in the readme, my hello-world app starts just fine.

Some things to check:

- Do you still have the original containers running? Can you check inside the mesosmaster container to see whether cron is running?
- If you `git ls-remote root@git:/root/dockercloud-hello-world.git`, is there a tag along the lines of: `9cdf957d3fbbb61fa17388adb2d8e282446271fc	refs/tags/paasta-testcluster.everything-20160809T031117-deploy`?
- If you enter the mesosmaster container with `docker exec` and run `git ls-remote root@git:/root/dockercloud-hello-world.git`, does it successfully run?

**Comment by mattmb** [comment] 2016-08-09 09:41
Glad to see this is closer to working @BenjaminDavison 

Firstly, the marathon status is probably a red herring. I think paasta shows it as critical if there are no services started.

What should happen after you run `paasta mark-for-deployment` is a cron job will generate a `deployments.json` alongside the service definitions in example services. If you `docker exec` into the mesosmaster or you can `ssh mesosmaster` from the playground container, you should be able to see the output from the cron jobs in `/var/log/syslog`. My first guess would be that the cron job is having trouble writing out the file.

Btw, I tried out docker for mac the other day and didn't have the same issue you had. I had to change one of the volume mounts from `/var/...` to `/private/var/...` but other than that it worked fine. Maybe we're on different versions or have different settings for the file sharing?

**Comment by BenjaminDavison** [comment] 2016-08-09 14:42
Thanks all for looking into this.

@EvanKrall How do you know when everything has finished starting up?

Running from playground:

```
root@360e0b08b10e:/tmp/dockercloud-hello-world# git ls-remote root@git:/root/dockercloud-hello-world.git
Warning: Permanently added 'git,172.18.0.3' (ECDSA) to the list of known hosts.
9cdf957d3fbbb61fa17388adb2d8e282446271fc	HEAD
9cdf957d3fbbb61fa17388adb2d8e282446271fc	refs/heads/master
a16fa3b31aa3beaa8ec9356a64304965b1fe86d6	refs/heads/staging
9cdf957d3fbbb61fa17388adb2d8e282446271fc	refs/tags/paasta-testcluster.everything-20160809T105558-deploy
```

Running from mesosmaster:

```
root@e261f5137c03:~# git ls-remote root@git:/root/dockercloud-hello-world.git
Warning: Permanently added 'git,172.18.0.3' (ECDSA) to the list of known hosts.
9cdf957d3fbbb61fa17388adb2d8e282446271fc	HEAD
9cdf957d3fbbb61fa17388adb2d8e282446271fc	refs/heads/master
a16fa3b31aa3beaa8ec9356a64304965b1fe86d6	refs/heads/staging
9cdf957d3fbbb61fa17388adb2d8e282446271fc	refs/tags/paasta-testcluster.everything-20160809T105558-deploy
```

The cron output from mesosmaster (shortened):
```
Aug  9 10:56:01 e261f5137c03 cron[211]: (*system*delete_old_marathon_deployments) INSECURE MODE (group/other writable) (/etc/cron.d/delete_old_marathon_deployments)
Aug  9 10:56:01 e261f5137c03 cron[211]: (*system*cleanup_marathon_jobs) INSECURE MODE (group/other writable) (/etc/cron.d/cleanup_marathon_jobs)
Aug  9 10:56:01 e261f5137c03 cron[211]: (*system*deploy_marathon_services) INSECURE MODE (group/other writable) (/etc/cron.d/deploy_marathon_services)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*autoscale_services) INSECURE MODE (group/other writable) (/etc/cron.d/autoscale_services)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*paasta_generate_all_deployments) INSECURE MODE (group/other writable) (/etc/cron.d/paasta_generate_all_deployments)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*cleanup_chronos_jobs) INSECURE MODE (group/other writable) (/etc/cron.d/cleanup_chronos_jobs)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*deploy_chronos_jobs) INSECURE MODE (group/other writable) (/etc/cron.d/deploy_chronos_jobs)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*delete_old_marathon_deployments) INSECURE MODE (group/other writable) (/etc/cron.d/delete_old_marathon_deployments)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*cleanup_marathon_jobs) INSECURE MODE (group/other writable) (/etc/cron.d/cleanup_marathon_jobs)
Aug  9 10:57:01 e261f5137c03 cron[211]: (*system*deploy_marathon_services) INSECURE MODE (group/other writable) (/etc/cron.d/deploy_marathon_services)
```

So it looks like cron is running fine.

@mattmb: You say it should generate a deployments.json, where would that be found?

Thanks,

Ben

**Comment by EvanKrall** [comment] 2016-08-09 17:31
deployments.json should end up in each service's directory under /nail/etc/services, so /nail/etc/services/happy-hour/deployments.json

I was just looking at `ps auxwwf` on my box to figure out when things had finished.

**Comment by BenjaminDavison** [comment] 2016-08-11 15:23
So it looks like deployments.json never gets created.

I'll try and do a little more debugging, but any pointers where I should look would be helpful.

Thanks,

Ben

**Comment by mattmb** [comment] 2016-12-13 11:50
I'm going to close this for now. I made some changes recently which hopefully make these sort of problems go away: https://github.com/Yelp/paasta/pull/913

**Closed by mattmb** 2016-12-13 11:50 UTC
