### ISSUE TITLE
Migrate from mesos.cli to dcos-cli

### ISSUE THREAD

**Issue by nhandler** [Yelp/paasta#399] opened 2016-04-05 17:30 UTC
mesos.cli is deprecated. We will need to migrate to dcos-cli.

**Comment by Rob-Johnson** [comment] 2016-04-06 13:34
dupe of internal PAASTA-869

**Comment by solarkennedy** [comment] 2016-09-20 22:16
I hereby declare this done/wontfix

**Closed by solarkennedy** 2016-09-20 22:16 UTC
